<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>BlazormeStreamSaver</RootNamespace>
    <AssemblyName>Blazorme.StreamSaver</AssemblyName>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Authors>melihercan</Authors>
    <Description>JSInterop of StreamSaver (https://github.com/jimmywarting/StreamSaver.js) package for Blazor WASM. 
With this package, you can download files by writing incoming data chunks directly to the file instead of accumulating them in memory. That will prevent memory overflows for very large files.</Description>
    <Copyright>melihercan2021</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>me.png</PackageIcon>
    <PackageIconUrl />
    <RepositoryUrl>https://github.com/melihercan/Blazorme</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>blazor file download writable stream</PackageTags>
    <PackageReleaseNotes>Creation</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\doc\me.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
