<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.24.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.11" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Diff\Diff.csproj" />
    <ProjectReference Include="..\Split\Split.csproj" />
    <ProjectReference Include="..\StreamSaver\StreamSaver.csproj" />
    <ProjectReference Include="..\TestHost\TestHost.csproj" />
  </ItemGroup>

</Project>
